/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.loan;

import static com.sun.org.apache.bcel.internal.Repository.instanceOf;
import domain.Library;
import file.AudiovisualFile;
import file.BookFile;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import materialRegistration.Audiovisual;
import materialRegistration.Book;
import materialRegistration.Laptop;

/**
 *
 * @author CASA
 */
public class AudiovisualLoanForm extends javax.swing.JFrame {

    
    private int counter = 0;
    private int lettersLength = 0;
    private Library library = new Library(); 
    DefaultTableModel model;
    //private List<Tuple> searches = new ArrayList<>();
    private List<Audiovisual> audiovs = new ArrayList<>();
    /**
     * Creates new form BookLoanForm
     */
    public AudiovisualLoanForm() {
        initComponents();
    }

    private void cleanTable() {
       model = (DefaultTableModel) this.searchAudiovTable.getModel();
       model.setRowCount(0);
       searchAudiovTable.setModel(model);
   
   }

   private void loadJTable() {
       
       model = (DefaultTableModel) this.searchAudiovTable.getModel();
       model.setRowCount(0);
        
       for (int i = 0; i < audiovs.size(); i++){    
            model.addRow(new Object[]{
                audiovs.get(i) instanceof materialRegistration.Laptop? "Laptop" : "Proyector",
                audiovs.get(i).getBrand(),
                audiovs.get(i).getModel()
                
            });
        }

        this.searchAudiovTable.setModel(model);
       
         
   }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        studentIDtxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        avLoanBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        searchAudiovTable = new javax.swing.JTable();
        searchAudiovTextField = new javax.swing.JTextField();

        jLabel1.setText("jLabel1");

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Audiovisual loan");

        studentIDtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentIDtxtActionPerformed(evt);
            }
        });

        jLabel4.setText("Student ID:");

        avLoanBtn.setText("Take material on a loan");
        avLoanBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                avLoanBtnMouseClicked(evt);
            }
        });

        searchAudiovTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Type", "Brand", "Model"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        searchAudiovTable.setAutoscrolls(false);
        searchAudiovTable.setFocusCycleRoot(true);
        jScrollPane1.setViewportView(searchAudiovTable);

        searchAudiovTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchAudiovTextFieldKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(searchAudiovTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(studentIDtxt)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(avLoanBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(searchAudiovTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(studentIDtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(258, 258, 258)
                        .addComponent(avLoanBtn)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void studentIDtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentIDtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studentIDtxtActionPerformed

    private void searchAudiovTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchAudiovTextFieldKeyReleased
        // TODO add your handling code here:
if ("".equals(this.searchAudiovTextField.getText().trim())) {
            this.cleanTable();
            counter = 0;
            this.library.deleteALLBooks();
        }
        else if (this.counter == 0 && this.searchAudiovTextField.getText().trim()  != "") {
            
            AudiovisualFile avf = new AudiovisualFile();
            String letters = this.searchAudiovTextField.getText();
            List<List<Audiovisual>> audiovsList = new ArrayList<>();
            this.audiovs = avf.getAudioVs(letters);
            System.out.print("ENTER");
            //agrega una lista de listas de libros
            this.library.setAudiovisualsList(audiovsList); //bookFile.getBooks(letters);
            //longitud hasta el momento de letras, si esta disminuye, deben de borrarse
            //de esa lista
            //si la cantidad de letras cambia, de debe de ver cuantas
            this.lettersLength = letters.length();
            //agrega los libros a la lista de listas. Donde cada una contiene
            //la ultima busqueda y de esa ultima se hara la siguiente.
            library.addAudiovsToList(audiovs);
            this.loadJTable();
            //populate JTable
            counter++;
        }
        else {

            if (this.lettersLength > this.searchAudiovTextField.getText().length()) {
                this.library.deleteAudiovsList(counter - 1);
                counter--;
            } else if (!this.library.getAudiovisualsList().get(counter-1).isEmpty()) {
                //retorna la nueva busqueda 
                List<Audiovisual> newaudiovisualList = this.library.searchAudiovisual(this.searchAudiovTextField.getText(), counter-1);


                //agrega e=la nueva lista a la lista de listas
                library.addAudiovsToList(newaudiovisualList);
                this.repaint();
                
                //settea la nueva lista en la lista utilizada para hacer la jtable
                this.audiovs = newaudiovisualList;

                //populate JTable
               
                 this.loadJTable();
            
            
            } else {
                JOptionPane.showMessageDialog(rootPane, "No Books", 
                    "Error", JOptionPane.ERROR_MESSAGE);
                counter = 0;
                this.library.deleteALLAudiovs();
                
            }
            
            
        
        }

    }//GEN-LAST:event_searchAudiovTextFieldKeyReleased

    private void avLoanBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_avLoanBtnMouseClicked
                try{
        Date today = new Date();
        int rowSelected = this.searchAudiovTable.getSelectedRow();
        
        // si efectivamente hay algo seleccionado en la tabla
        if (rowSelected != -1) {
            String model = 
                    searchAudiovTable.getValueAt
                            (searchAudiovTable.getSelectedRow(), 1).toString();
            
           studentRegistration.Student loanedStudent =
                    file.StudentFile.getInstance()
                     .getStudentByID(Integer.parseInt(studentIDtxt.getText()));
           if (loanedStudent != null){
        
                materialRegistration.Audiovisual loanedAV = 
                        domain.Library.getInstance().getAVbyModel(model);
                
                
               
                domain.Library.getInstance().registerAudiovisual(loanedAV);

                JOptionPane.showMessageDialog(rootPane,"Loan registered successfully",
                       "Success", JOptionPane.ERROR_MESSAGE);
                
           }else{
               JOptionPane.showMessageDialog(rootPane, "Student not registered",
                       "Error", JOptionPane.ERROR_MESSAGE);
           }
   
        }
        }catch(Exception e){
            System.err.println(e.getMessage());
        }
    }//GEN-LAST:event_avLoanBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AudiovisualLoanForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AudiovisualLoanForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AudiovisualLoanForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AudiovisualLoanForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AudiovisualLoanForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton avLoanBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable searchAudiovTable;
    private javax.swing.JTextField searchAudiovTextField;
    private javax.swing.JTextField studentIDtxt;
    // End of variables declaration//GEN-END:variables
}
