/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.loan;

import domain.Library;
import file.BookFile;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.Document;
import materialRegistration.Book;
import util.Tuple;
/**
 *
 * @author CASA
 */
public class BookLoanForm extends javax.swing.JFrame {

    /**
     * Creates new form BookLoanForm
     */
    
    private int counter = 0;
    private int lettersLength = 0;
    private Library library = new Library(); 
    DefaultTableModel model;
    //private List<Tuple> searches = new ArrayList<>();
    private List<Book> books = new ArrayList<>();
   public BookLoanForm() {
        initComponents();
        
    }

   private void loadJTable() {
       
       model = (DefaultTableModel) this.searchBookTable.getModel();
       model.setRowCount(0);
       //model.addColumn("Name");
      // model.addColumn("Author");
       //model.addColumn("ISBN");
       //model.addColumn("Year");
       
       for (int i = 0; i < books.size(); i++){    
            model.addRow(new Object[]{
                books.get(i).getName(),
                books.get(i).getAuthor(),
                books.get(i).getISBN(),
                books.get(i).getYear()
            });
        }

        searchBookTable.setModel(model);
       
         
   }
   
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        studentIDtxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        searchBookTable = new javax.swing.JTable();
        searchBookTextField = new javax.swing.JTextField();

        jLabel1.setText("jLabel1");

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Book loan");

        studentIDtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentIDtxtActionPerformed(evt);
            }
        });

        jLabel4.setText("Student ID:");

        jButton1.setText("Take book on a loan");

        searchBookTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Name", "Author", "ISBN", "Year"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(searchBookTable);

        searchBookTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBookTextFieldActionPerformed(evt);
            }
        });
        searchBookTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchBookTextFieldKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(searchBookTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(studentIDtxt)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(searchBookTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(studentIDtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(258, 258, 258)
                        .addComponent(jButton1)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void studentIDtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentIDtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studentIDtxtActionPerformed

    private void searchBookTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBookTextFieldActionPerformed
        // TODO add your handling code here:
        // este codigo va en el listener, es ejecutado cada vez que cambia 
      
        
    }//GEN-LAST:event_searchBookTextFieldActionPerformed

    private void searchBookTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchBookTextFieldKeyReleased
        // TODO add your handling code here:
        if (this.counter == 0 && this.searchBookTextField.getText().trim()  != "") {
            File file = new File("./files/bookFile.dat");
            try {
                BookFile bookFile = new BookFile(file);
                String letters = this.searchBookTextField.getText();
                List<List<Book>> bookList = new ArrayList<>();
                this.books = bookFile.getBooks(letters);
                System.out.print("ENTER");
                //agrega una lista de listas de libros
                this.library.setBookList(bookList); //bookFile.getBooks(letters);
                
                
                //longitud hasta el momento de letras, si esta disminuye, deben de borrarse
                //de esa lista 
                //si la cantidad de letras cambia, de debe de ver cuantas 
                this.lettersLength = letters.length();
                
                
                //agrega los libros a la lista de listas. Donde cada una contiene
               //la ultima busqueda y de esa ultima se hara la siguiente. 
               library.addBooksToList(books);
               
               this.loadJTable();
                //populate JTable
                
                
                counter++;
            } catch (IOException ex) {
                Logger.getLogger(BookLoanForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else {

            if (this.lettersLength > this.searchBookTextField.getText().length()) {
                this.library.deleteBooksList(counter - 1);
                counter--;
            } else if (!this.library.getBookList().get(counter-1).isEmpty()) {
                //retorna la nueva busqueda 
                List<Book> newBookList = this.library.searchBook(this.searchBookTextField.getText(), counter-1);


                //agrega e=la nueva lista a la lista de listas
                library.addBooksToList(newBookList);
                this.repaint();
                
                //settea la nueva lista en la lista utilizada para hacer la jtable
                this.books = newBookList;

                //populate JTable
               
                 this.loadJTable();
            
            
            } else {
                JOptionPane.showMessageDialog(rootPane, "No Books", 
                    "Error", JOptionPane.ERROR_MESSAGE);
                counter = 0;
                this.library.deleteALLBooks();
                
            }
            
            
        
        }
    }//GEN-LAST:event_searchBookTextFieldKeyReleased
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookLoanForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookLoanForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookLoanForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookLoanForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BookLoanForm().setVisible(true);
            }
        });
    }
    
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable searchBookTable;
    private javax.swing.JTextField searchBookTextField;
    private javax.swing.JTextField studentIDtxt;
    // End of variables declaration//GEN-END:variables

    

}
