/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.material;

import materialRegistration.LaptopOS;

/**
 *
 * @author CASA
 */
public class AudiovisualRegister extends javax.swing.JFrame {

    /**
     * Creates new form AudiovisualRegister
     */
    public AudiovisualRegister() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        laptopDialog = new javax.swing.JDialog();
        laptioInfoLbl = new javax.swing.JLabel();
        osBox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        acceptLapInfoBTN = new javax.swing.JButton();
        projectorDialog = new javax.swing.JDialog();
        laptioInfoLbl1 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        acceptLapInfoBTN1 = new javax.swing.JButton();
        registerLbl = new javax.swing.JLabel();
        titleLbl = new javax.swing.JLabel();
        modelAVTxt = new javax.swing.JTextField();
        brandAVLbl = new javax.swing.JLabel();
        showYearLbl = new javax.swing.JLabel();
        brandAVTxt = new javax.swing.JTextField();
        publisherTxt = new javax.swing.JTextField();
        yearLbl1 = new javax.swing.JLabel();
        registerBookBTN = new javax.swing.JButton();
        avTypeBOX = new javax.swing.JComboBox<>();

        laptioInfoLbl.setFont(new java.awt.Font("Blackout 2AM", 0, 36)); // NOI18N
        laptioInfoLbl.setText("Laptop information");

        osBox.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        osBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Windows", "MacOS", "Linux", "Other" }));
        osBox.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                osBoxFocusGained(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setText("Operative System:");

        jTextField1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setText("Screen size (inches):");

        acceptLapInfoBTN.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        acceptLapInfoBTN.setText("Accept");

        javax.swing.GroupLayout laptopDialogLayout = new javax.swing.GroupLayout(laptopDialog.getContentPane());
        laptopDialog.getContentPane().setLayout(laptopDialogLayout);
        laptopDialogLayout.setHorizontalGroup(
            laptopDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(laptopDialogLayout.createSequentialGroup()
                .addContainerGap(72, Short.MAX_VALUE)
                .addGroup(laptopDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(laptopDialogLayout.createSequentialGroup()
                        .addGroup(laptopDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, laptopDialogLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(laptopDialogLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(osBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, laptopDialogLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(laptopDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(acceptLapInfoBTN)
                            .addComponent(laptioInfoLbl))
                        .addGap(63, 63, 63))))
        );
        laptopDialogLayout.setVerticalGroup(
            laptopDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(laptopDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(laptioInfoLbl)
                .addGap(44, 44, 44)
                .addGroup(laptopDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(osBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(34, 34, 34)
                .addGroup(laptopDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addComponent(acceptLapInfoBTN)
                .addGap(28, 28, 28))
        );

        laptioInfoLbl1.setFont(new java.awt.Font("Blackout 2AM", 0, 36)); // NOI18N
        laptioInfoLbl1.setText("Projector information");

        jTextField2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel4.setText("Lumens:");

        acceptLapInfoBTN1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        acceptLapInfoBTN1.setText("Accept");

        javax.swing.GroupLayout projectorDialogLayout = new javax.swing.GroupLayout(projectorDialog.getContentPane());
        projectorDialog.getContentPane().setLayout(projectorDialogLayout);
        projectorDialogLayout.setHorizontalGroup(
            projectorDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, projectorDialogLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(projectorDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(acceptLapInfoBTN1)
                    .addComponent(laptioInfoLbl1))
                .addGap(63, 63, 63))
            .addGroup(projectorDialogLayout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        projectorDialogLayout.setVerticalGroup(
            projectorDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(projectorDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(laptioInfoLbl1)
                .addGap(44, 44, 44)
                .addGroup(projectorDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(acceptLapInfoBTN1)
                .addGap(88, 88, 88))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        registerLbl.setFont(new java.awt.Font("Blackout 2AM", 0, 18)); // NOI18N
        registerLbl.setText("Audiovisual material registration");

        titleLbl.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        titleLbl.setText("Model:");

        modelAVTxt.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        brandAVLbl.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        brandAVLbl.setText("Brand");

        showYearLbl.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        brandAVTxt.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        publisherTxt.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        yearLbl1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        yearLbl1.setText("Serial number:");

        registerBookBTN.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        registerBookBTN.setText("Accept");

        avTypeBOX.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laptop", "Projector", "Other" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(showYearLbl)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(yearLbl1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(registerBookBTN)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(avTypeBOX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(modelAVTxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE)
                                .addComponent(titleLbl, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(brandAVLbl, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(brandAVTxt, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(publisherTxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(registerLbl))
                .addGap(47, 47, 47))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(registerLbl)
                .addGap(26, 26, 26)
                .addComponent(titleLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(modelAVTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(brandAVLbl)
                .addGap(4, 4, 4)
                .addComponent(brandAVTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(showYearLbl)
                .addGap(67, 67, 67)
                .addComponent(yearLbl1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(publisherTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(avTypeBOX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(registerBookBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void osBoxFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_osBoxFocusGained
        
        
    }//GEN-LAST:event_osBoxFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AudiovisualRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AudiovisualRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AudiovisualRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AudiovisualRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AudiovisualRegister().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acceptLapInfoBTN;
    private javax.swing.JButton acceptLapInfoBTN1;
    private javax.swing.JComboBox<String> avTypeBOX;
    private javax.swing.JLabel brandAVLbl;
    private javax.swing.JTextField brandAVTxt;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel laptioInfoLbl;
    private javax.swing.JLabel laptioInfoLbl1;
    private javax.swing.JDialog laptopDialog;
    private javax.swing.JTextField modelAVTxt;
    private javax.swing.JComboBox<String> osBox;
    private javax.swing.JDialog projectorDialog;
    private javax.swing.JTextField publisherTxt;
    private javax.swing.JButton registerBookBTN;
    private javax.swing.JLabel registerLbl;
    private javax.swing.JLabel showYearLbl;
    private javax.swing.JLabel titleLbl;
    private javax.swing.JLabel yearLbl1;
    // End of variables declaration//GEN-END:variables
}
