/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.material;

/**
 *
 * @author CASA
 */
public class BookRegister extends javax.swing.JFrame {

    /**
     * Creates new form AudiovisualRegister
     */
    public BookRegister() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        registerLbl = new javax.swing.JLabel();
        titleLbl = new javax.swing.JLabel();
        titleTxt = new javax.swing.JTextField();
        authorLbl = new javax.swing.JLabel();
        ISBN = new javax.swing.JFormattedTextField();
        authorLbl1 = new javax.swing.JLabel();
        yearLbl = new javax.swing.JLabel();
        showYearLbl = new javax.swing.JLabel();
        authorTxt1 = new javax.swing.JTextField();
        publisherTxt = new javax.swing.JTextField();
        yearLbl1 = new javax.swing.JLabel();
        yearTxt = new javax.swing.JTextField();
        registerBookBTN = new javax.swing.JButton();
        digitalRdoBtn = new javax.swing.JRadioButton();
        physicalRdoBtn = new javax.swing.JRadioButton();
        yearLbl2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        registerLbl.setFont(new java.awt.Font("Blackout 2AM", 0, 18)); // NOI18N
        registerLbl.setText("Book registration");

        titleLbl.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        titleLbl.setText("Title:");

        titleTxt.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        authorLbl.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        authorLbl.setText("Author:");

        try {
            ISBN.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###-#-####-####-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ISBN.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        authorLbl1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        authorLbl1.setText("ISBN:");

        yearLbl.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        yearLbl.setText("Year:");

        showYearLbl.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        authorTxt1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        publisherTxt.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        yearLbl1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        yearLbl1.setText("Publisher:");

        yearTxt.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        yearTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                yearTxtKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                yearTxtKeyTyped(evt);
            }
        });

        registerBookBTN.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        registerBookBTN.setText("Accept");

        buttonGroup1.add(digitalRdoBtn);
        digitalRdoBtn.setText("Digital");

        buttonGroup1.add(physicalRdoBtn);
        physicalRdoBtn.setText("Physical");

        yearLbl2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        yearLbl2.setText("Type:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(registerLbl))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(60, 60, 60)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(yearLbl)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(showYearLbl))
                                .addComponent(yearTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(physicalRdoBtn)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(digitalRdoBtn))
                                .addComponent(yearLbl2))
                            .addGap(19, 19, 19))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(47, 47, 47)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(yearLbl1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(registerBookBTN)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(authorLbl1, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(titleTxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE)
                                        .addComponent(titleLbl, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(authorLbl, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(ISBN, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(authorTxt1, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(publisherTxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addGap(47, 47, 47))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(registerLbl)
                .addGap(26, 26, 26)
                .addComponent(titleLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(titleTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(authorLbl)
                .addGap(4, 4, 4)
                .addComponent(authorTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(physicalRdoBtn)
                            .addComponent(digitalRdoBtn)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(yearLbl)
                            .addComponent(showYearLbl)
                            .addComponent(yearLbl2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(yearTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(yearLbl1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(publisherTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(authorLbl1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ISBN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(registerBookBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void yearTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_yearTxtKeyTyped
        
    
    }//GEN-LAST:event_yearTxtKeyTyped

    private void yearTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_yearTxtKeyReleased
        if (!Character.isDigit(yearTxt.getText()
                .charAt(yearTxt.getText().length()-1))){
            yearTxt.setText(yearTxt.getText()
                    .substring(0, yearTxt.getText().length()-1));
        }else if (yearTxt.getText().length() > 4){
            yearTxt.setText(yearTxt.getText()
                    .substring(0, yearTxt.getText().length()-1));
        }
    }//GEN-LAST:event_yearTxtKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BookRegister().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField ISBN;
    private javax.swing.JLabel authorLbl;
    private javax.swing.JLabel authorLbl1;
    private javax.swing.JTextField authorTxt1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton digitalRdoBtn;
    private javax.swing.JRadioButton physicalRdoBtn;
    private javax.swing.JTextField publisherTxt;
    private javax.swing.JButton registerBookBTN;
    private javax.swing.JLabel registerLbl;
    private javax.swing.JLabel showYearLbl;
    private javax.swing.JLabel titleLbl;
    private javax.swing.JTextField titleTxt;
    private javax.swing.JLabel yearLbl;
    private javax.swing.JLabel yearLbl1;
    private javax.swing.JLabel yearLbl2;
    private javax.swing.JTextField yearTxt;
    // End of variables declaration//GEN-END:variables
}
