/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.student;

import javax.swing.JOptionPane;
import javax.swing.SpinnerListModel;
import javax.swing.SpinnerModel;
import studentRegistration.Career;

/**
 *
 * @author CASA
 */
public class StudentRegistrationForm extends javax.swing.JFrame {

    /**
     * Creates new form StudentRegistrationForm
     */
    public StudentRegistrationForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        idStuRegTxt = new javax.swing.JTextField();
        nameTxt = new javax.swing.JTextField();
        lnameTxt = new javax.swing.JTextField();
        careerSpin = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        registerStudentBTN = new javax.swing.JButton();

        jLabel2.setText("jLabel2");

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Student registration");

        idStuRegTxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        idStuRegTxt.setText("ID");
        idStuRegTxt.setDoubleBuffered(true);
        idStuRegTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idStuRegTxtActionPerformed(evt);
            }
        });

        nameTxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nameTxt.setText("Name");
        nameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTxtActionPerformed(evt);
            }
        });

        lnameTxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lnameTxt.setText("Last name");
        lnameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lnameTxtActionPerformed(evt);
            }
        });

        careerSpin.setModel(new javax.swing.SpinnerListModel(new String[] {"Item 0", "Item 1", "Item 2", "Item 3"}));
        careerSpin.setOpaque(false);

        jLabel3.setText("Career:");

        registerStudentBTN.setText("Register student");
        registerStudentBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registerStudentBTNMouseClicked(evt);
            }
        });
        registerStudentBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerStudentBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(100, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(idStuRegTxt)
                    .addComponent(nameTxt, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lnameTxt)
                    .addComponent(careerSpin)
                    .addComponent(registerStudentBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(91, 91, 91))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(47, 47, 47)
                .addComponent(idStuRegTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(nameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lnameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(3, 3, 3)
                .addComponent(careerSpin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(registerStudentBTN)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void idStuRegTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idStuRegTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idStuRegTxtActionPerformed

    private void nameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTxtActionPerformed

    private void lnameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lnameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lnameTxtActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        /*SpinnerListModel model = new SpinnerListModel();
        model.setValue(studentRegistration.Career.COMPUTER);
        model.setValue(studentRegistration.Career.MECHATRONICS);
        model.setValue(studentRegistration.Career.ELECTRONIC);
        careerSpin.setModel(model);*/
    }//GEN-LAST:event_formWindowGainedFocus

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        Object[] careers = {util.Conversions
                .career2str(studentRegistration.Career.COMPUTER),
            util.Conversions
                .career2str(studentRegistration.Career.MECHATRONICS),
            util.Conversions
                .career2str(studentRegistration.Career.ELECTRONIC)};
        SpinnerListModel model = new SpinnerListModel(careers);
       
        careerSpin.setModel(model);
    }//GEN-LAST:event_formWindowActivated

    private void registerStudentBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerStudentBTNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registerStudentBTNActionPerformed

    private void registerStudentBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerStudentBTNMouseClicked
        int ID = 0;
        try{
            ID = Integer.parseInt(idStuRegTxt.getText());
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, "Must enter a value", 
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
        String name = nameTxt.getText();
        String lastname = lnameTxt.getText();
        studentRegistration.Career career  = util.Conversions
                .str2career(careerSpin.getValue().toString());
        
        if (ID != 0 && name != "Name" && lastname != "Last name"){
            studentRegistration.Student newStudent =
            new studentRegistration
                .Student(ID, name, lastname, career);
            try{
                domain.Library.getInstance().registerStudent(newStudent);
            }catch(Exception e){
                System.err.println(e.toString());
            }   
        }else{
            
            JOptionPane.showMessageDialog(rootPane, "Must enter a value", 
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_registerStudentBTNMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentRegistrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentRegistrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentRegistrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentRegistrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentRegistrationForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner careerSpin;
    private javax.swing.JTextField idStuRegTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JTextField lnameTxt;
    private javax.swing.JTextField nameTxt;
    private javax.swing.JButton registerStudentBTN;
    // End of variables declaration//GEN-END:variables
}
